#!/usr/bin/env bash
set -eo pipefail

# Retry `yarn install` up to three times.
#
# See https://github.com/yarnpkg/yarn/issues/7521#issuecomment-550057386
# (Revisit this once the above issue is resolved.)
for i in 1 2 3; do yarn install --non-interactive --frozen-lockfile --prefer-offline && break; done
